-- MySQL Script generated by MySQL Workbench
-- 2020년 09월 02일 (수) 오전 11시 35분 31초
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema droneDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema droneDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `droneDB` DEFAULT CHARACTER SET utf8 ;
USE `droneDB` ;

-- -----------------------------------------------------
-- Table `droneDB`.`gps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `droneDB`.`gps` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `altitude` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
