-- MySQL Script generated by MySQL Workbench
-- 2020년 09월 01일 (화) 오후 12시 10분 38초
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema game
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema game
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `game` DEFAULT CHARACTER SET utf8 ;
USE `game` ;

-- -----------------------------------------------------
-- Table `game`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logInId` NVARCHAR(1024) NOT NULL,
  `password` NVARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`map` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` NVARCHAR(1024) NOT NULL,
  `bgImagePath` NVARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`tile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`tile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` NVARCHAR(1024) NOT NULL,
  `isMovable` TINYINT(1) NOT NULL,
  `imagePath` NVARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`portal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`portal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mapId1` INT NOT NULL,
  `position1` TINYINT(4) NOT NULL,
  `mapId2` INT NOT NULL,
  `position2` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_portal_map1_idx` (`mapId1` ASC),
  INDEX `fk_portal_map2_idx` (`mapId2` ASC),
  CONSTRAINT `fk_portal_map1`
    FOREIGN KEY (`mapId1`)
    REFERENCES `game`.`map` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_portal_map2`
    FOREIGN KEY (`mapId2`)
    REFERENCES `game`.`map` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`logInLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`logInLog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `playerId` INT NOT NULL,
  `time` DATETIME NOT NULL,
  `isLogIn` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_logInLog_player1_idx` (`playerId` ASC),
  CONSTRAINT `fk_logInLog_player1`
    FOREIGN KEY (`playerId`)
    REFERENCES `game`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`character` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `playerId` INT NOT NULL,
  `nickname` NVARCHAR(1024) NOT NULL,
  `gender` TINYINT(1) NOT NULL,
  `life` FLOAT NOT NULL,
  `attack` FLOAT NOT NULL,
  `defense` FLOAT NOT NULL,
  `attackSpeed` FLOAT NOT NULL,
  `mapId` INT NOT NULL,
  `position` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_character_map1_idx` (`mapId` ASC),
  INDEX `fk_character_player1_idx` (`playerId` ASC),
  CONSTRAINT `fk_character_map1`
    FOREIGN KEY (`mapId`)
    REFERENCES `game`.`map` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_player1`
    FOREIGN KEY (`playerId`)
    REFERENCES `game`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` NVARCHAR(1024) NOT NULL,
  `imagePath` NVARCHAR(1024) NOT NULL,
  `life` FLOAT NULL,
  `attack` FLOAT NULL,
  `defense` FLOAT NULL,
  `attackSpeed` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`ownedItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`ownedItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `itemId` INT NOT NULL,
  `characterId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_concreteItem_item1_idx` (`itemId` ASC),
  INDEX `fk_concreteItem_character1_idx` (`characterId` ASC),
  CONSTRAINT `fk_concreteItem_item1`
    FOREIGN KEY (`itemId`)
    REFERENCES `game`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_concreteItem_character1`
    FOREIGN KEY (`characterId`)
    REFERENCES `game`.`character` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`concreteTile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`concreteTile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mapId` INT NOT NULL,
  `tileId` INT NOT NULL,
  `position` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_concreteTile_map1_idx` (`mapId` ASC),
  INDEX `fk_concreteTile_tile1_idx` (`tileId` ASC),
  CONSTRAINT `fk_concreteTile_map1`
    FOREIGN KEY (`mapId`)
    REFERENCES `game`.`map` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_concreteTile_tile1`
    FOREIGN KEY (`tileId`)
    REFERENCES `game`.`tile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`enemy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`enemy` (
  `id` INT NOT NULL,
  `name` NVARCHAR(1024) NOT NULL,
  `imagePath` NVARCHAR(1024) NOT NULL,
  `life` FLOAT NOT NULL,
  `attack` FLOAT NOT NULL,
  `defense` FLOAT NOT NULL,
  `attackSpeed` FLOAT NOT NULL,
  `rewardItemId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enemy_item1_idx` (`rewardItemId` ASC),
  CONSTRAINT `fk_enemy_item1`
    FOREIGN KEY (`rewardItemId`)
    REFERENCES `game`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`object` (
  `id` INT NOT NULL,
  `itemId` INT NOT NULL,
  `mapId` INT NOT NULL,
  `position` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_object_item1_idx` (`itemId` ASC),
  INDEX `fk_object_map1_idx` (`mapId` ASC),
  CONSTRAINT `fk_object_item1`
    FOREIGN KEY (`itemId`)
    REFERENCES `game`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_object_map1`
    FOREIGN KEY (`mapId`)
    REFERENCES `game`.`map` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`action` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lifeCost` FLOAT NULL,
  `actionName` NVARCHAR(1024) NOT NULL,
  `objectTargetId` INT NULL,
  `enemyTargetId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_action_enemy1_idx` (`enemyTargetId` ASC),
  INDEX `fk_action_object1_idx` (`objectTargetId` ASC),
  CONSTRAINT `fk_action_enemy1`
    FOREIGN KEY (`enemyTargetId`)
    REFERENCES `game`.`enemy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_action_object1`
    FOREIGN KEY (`objectTargetId`)
    REFERENCES `game`.`object` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`actionLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`actionLog` (
  `id` INT NOT NULL,
  `characterId` INT NOT NULL,
  `actionId` INT NOT NULL,
  `objectTargetId` INT NULL,
  `enemyTargetId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actionLog_action1_idx` (`actionId` ASC),
  INDEX `fk_actionLog_character1_idx` (`characterId` ASC),
  INDEX `fk_actionLog_object1_idx` (`objectTargetId` ASC),
  INDEX `fk_actionLog_enemy1_idx` (`enemyTargetId` ASC),
  CONSTRAINT `fk_actionLog_action1`
    FOREIGN KEY (`actionId`)
    REFERENCES `game`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actionLog_character1`
    FOREIGN KEY (`characterId`)
    REFERENCES `game`.`character` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actionLog_object1`
    FOREIGN KEY (`objectTargetId`)
    REFERENCES `game`.`object` (`itemId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actionLog_enemy1`
    FOREIGN KEY (`enemyTargetId`)
    REFERENCES `game`.`enemy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`moveLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`moveLog` (
  `id` INT NOT NULL,
  `characterId` INT NOT NULL,
  `mapId` INT NOT NULL,
  `position` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_moveLog_map1_idx` (`mapId` ASC),
  INDEX `fk_moveLog_character1_idx` (`characterId` ASC),
  CONSTRAINT `fk_moveLog_map1`
    FOREIGN KEY (`mapId`)
    REFERENCES `game`.`map` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_moveLog_character1`
    FOREIGN KEY (`characterId`)
    REFERENCES `game`.`character` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`concreteEnemy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`concreteEnemy` (
  `id` INT NOT NULL,
  `enemyId` INT NOT NULL,
  `mapId` INT NOT NULL,
  `position` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_concreteEnemy_enemy1_idx` (`enemyId` ASC),
  INDEX `fk_concreteEnemy_map1_idx` (`mapId` ASC),
  CONSTRAINT `fk_concreteEnemy_enemy1`
    FOREIGN KEY (`enemyId`)
    REFERENCES `game`.`enemy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_concreteEnemy_map1`
    FOREIGN KEY (`mapId`)
    REFERENCES `game`.`map` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
